os: linux
dist: bionic
language: cpp

services:
  - docker

script:
  # Compile from source
  - sudo apt-get update
  - sudo apt-get install apt-utils -y
  - sudo apt-get install bsdmainutils -y
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository ppa:bitcoin/bitcoin -y
  - sudo apt-get update
  - sudo apt-get install make -y
  - sudo apt-get install gcc -y
  - sudo apt-get install g++ -y
  - sudo apt-get install pkg-config -y
  - sudo apt-get install autoconf -y
  - sudo apt-get install libtool -y
  - sudo apt-get install libboost-all-dev -y
  - sudo apt-get install libssl-dev -y
  - sudo apt-get install libevent-dev -y
  - sudo apt-get install libdb4.8-dev libdb4.8++-dev -y
  - ./autogen.sh
  - ./configure
  - make
